name: Build

on:
  push:

env:
  IMAGE_NAME: hiraishin
  DOCKER_FILE_PATH: Dockerfile

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: Add path for Poetry
        run: echo "::add-path::$HOME/.poetry/bin"

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Run Tests
        run: poetry run pytest tests/
